INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('João Silva', 'Desenvolvedor', 5000.00, '2023-01-15');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Maria Santos', 'Analista de Dados', 6000.00, '2022-11-20');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Carlos Oliveira', 'Gerente de Projetos', 8000.00, '2021-08-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Ana Costa', 'Engenheiro de Software', 5500.00, '2023-05-05');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Pedro Rocha', 'Designer UX/UI', 4800.00, '2023-02-28');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Juliana Pereira', 'Analista Financeiro', 5500.00, '2022-10-03');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Rafaela Oliveira', 'Desenvolvedor', 5200.00, '2023-04-12');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Lucas Martins', 'Analista de Sistemas', 6000.00, '2022-09-22');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Fernanda Almeida', 'Gerente de Marketing', 7500.00, '2021-12-18');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Márcio Souza', 'Desenvolvedor', 4800.00, '2023-03-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Aline Ferreira', 'Analista de Qualidade', 5500.00, '2022-07-05');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Paulo Lima', 'Analista de Dados', 6200.00, '2022-05-30');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Patrícia Santos', 'Designer Gráfico', 5000.00, '2023-02-18');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Roberto Pereira', 'Engenheiro de Software', 5800.00, '2023-01-05');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Carla Costa', 'Analista de Recursos Humanos', 5500.00, '2022-08-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Gustavo Oliveira', 'Analista de Sistemas', 6100.00, '2022-11-28');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Débora Martins', 'Desenvolvedor', 5300.00, '2023-03-15');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Luiz Ferreira', 'Analista Financeiro', 5800.00, '2022-06-20');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Camila Rodrigues', 'Analista de Marketing', 5700.00, '2022-09-03');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Andreia Lima', 'Engenheiro de Software', 5900.00, '2023-01-20');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Marcos Santos', 'Analista de Dados', 6400.00, '2022-04-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Isabela Oliveira', 'Analista de Qualidade', 5400.00, '2022-07-25');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Daniel Costa', 'Desenvolvedor', 5100.00, '2023-02-05');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Tatiane Pereira', 'Designer UX/UI', 4900.00, '2023-03-28');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Ricardo Almeida', 'Analista de Sistemas', 6200.00, '2022-08-22');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Mariana Fernandes', 'Gerente de Projetos', 7800.00, '2021-11-15');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('José Silva', 'Analista de Marketing', 5800.00, '2022-06-05');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Natália Martins', 'Analista de Recursos Humanos', 5700.00, '2022-09-20');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Leandro Santos', 'Engenheiro de Software', 6000.00, '2023-01-25');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Sandra Costa', 'Analista de Dados', 6300.00, '2022-04-28');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Roberto Oliveira', 'Analista de Qualidade', 5500.00, '2022-07-15');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Cristiane Lima', 'Desenvolvedor', 5400.00, '2023-04-05');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Guilherme Almeida', 'Analista Financeiro', 5900.00, '2022-06-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Ana Paula Santos', 'Designer Gráfico', 5100.00, '2023-03-03');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Marcio Pereira', 'Analista de Sistemas', 6300.00, '2022-08-18');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Tatiana Oliveira', 'Gerente de Projetos', 7700.00, '2021-10-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Luciana Silva', 'Analista de Marketing', 5900.00, '2022-05-05');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Rafael Ferreira', 'Analista de Recursos Humanos', 5600.00, '2022-10-20');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Camila Costa', 'Engenheiro de Software', 6100.00, '2023-02-15');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Leonardo Rodrigues', 'Analista de Dados', 6500.00, '2022-03-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Amanda Lima', 'Analista de Qualidade', 5600.00, '2022-08-05');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Anderson Oliveira', 'Desenvolvedor', 5200.00, '2023-05-28');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Silvia Fernandes', 'Analista Financeiro', 6000.00, '2022-07-22');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Diego Pereira', 'Designer Gráfico', 5300.00, '2023-01-28');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Beatriz Costa', 'Analista de Sistemas', 6400.00, '2022-06-15');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Julio Santos', 'Gerente de Projetos', 7600.00, '2021-12-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Monica Oliveira', 'Analista de Marketing', 6000.00, '2022-05-15');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Vitor Ferreira', 'Analista de Recursos Humanos', 5500.00, '2022-10-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Fernanda Silva', 'Engenheiro de Software', 6200.00, '2023-02-25');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Rodrigo Costa', 'Analista de Dados', 6600.00, '2022-03-28');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Carolina Lima', 'Analista de Qualidade', 5700.00, '2022-08-22');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Felipe Rodrigues', 'Desenvolvedor', 5300.00, '2023-04-15');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Mariana Oliveira', 'Analista Financeiro', 6100.00, '2022-07-10');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Renato Pereira', 'Designer UX/UI', 5400.00, '2023-02-03');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Fábio Santos', 'Analista de Sistemas', 6500.00, '2022-06-18');
INSERT INTO restrito.funcionarios (nome, cargo, salario, data_contratacao) VALUES ('Cintia Costa', 'Gerente de Projetos', 7400.00, '2022-12-05');